# Generated by Django 5.2.7 on 2025-10-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy 😊'), ('sad', 'Sad 😢'), ('energetic', 'Energetic ⚡'), ('calm', 'Calm 😌'), ('romantic', 'Romantic 💕'), ('angry', 'Angry 😠'), ('nostalgic', 'Nostalgic 🌅'), ('motivated', 'Motivated 💪')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_mood_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
