# Generated by Django 5.2.7 on 2025-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_userprofile_current_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.URLField(blank=True),
        ),
    ]
