# Generated by Django 5.2.7 on 2025-10-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_song_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='safepay_order_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='safepay_order_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
