# Generated by Django 5.2.7 on 2025-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_rename_safepay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
